"""add_email_verification

Revision ID: 4beaaa1a4c1c
Revises: 7840e9e94204
Create Date: 2026-09-15 08:35:48.137389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4beaaa1a4c1c'
down_revision = '7840e9e94204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('last_email_sent', sa.DateTime(), nullable=True))

    # UPDATE PENTING: Set pengguna lama menjadi terverifikasi agar tidak terkunci
    op.execute('UPDATE data_user SET is_verified = true')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_user', schema=None) as batch_op:
        batch_op.drop_column('last_email_sent')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
