"""Merge article_db and analytics_article into articles

Revision ID: 70078e6e70d1
Revises: 02d14166d7ed
Create Date: 2026-09-12 02:11:17.512081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70078e6e70d1'
down_revision = '02d14166d7ed'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Buat tabel 'articles' baru
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['data_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_user_id'), ['user_id'], unique=False)

    # 2. Migrasi data dari analytics_article dan article_db ke articles jika ada data
    op.execute("""
        INSERT INTO articles (id, title, category, author, description, published_at, user_id)
        SELECT 
            a.id, 
            a.title, 
            COALESCE(a.category, 'Umum'), 
            a.author, 
            adb.description, 
            a.published_at, 
            adb.user_id
        FROM analytics_article a
        LEFT JOIN article_db adb ON a.title = adb.title
        ON CONFLICT (id) DO NOTHING;
    """)

    # Sinkronkan sequence serial Postgres untuk articles.id
    op.execute("""
        SELECT setval(pg_get_serial_sequence('articles', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM articles;
    """)

    # 3. Lepas foreign key lama di analytics_visit_log sebelum drop tabel analytics_article
    with op.batch_alter_table('analytics_visit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_visit_log_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_visit_log_created_at'), ['created_at'], unique=False)
        batch_op.drop_constraint('analytics_visit_log_article_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'articles', ['article_id'], ['id'], ondelete='CASCADE')

    # 4. Sekarang aman drop tabel-tabel lama
    op.drop_table('article_db')
    op.drop_table('analytics_article')

    # 5. Indeks di data_user
    with op.batch_alter_table('data_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_data_user_username'), ['username'], unique=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_user_username'))
        batch_op.drop_index(batch_op.f('ix_data_user_email'))

    with op.batch_alter_table('analytics_visit_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('analytics_visit_log_article_id_fkey'), 'analytics_article', ['article_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_analytics_visit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_analytics_visit_log_article_id'))

    op.create_table('analytics_article',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_article_pkey'))
    )
    op.create_table('article_db',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['data_user.id'], name=op.f('article_db_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('article_db_pkey'))
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_user_id'))
        batch_op.drop_index(batch_op.f('ix_articles_title'))

    op.drop_table('articles')
    # ### end Alembic commands ###
