"""Add last_warning_message

Revision ID: b659271f9961
Revises: f88362d58ca8
Create Date: 2026-09-15 07:07:57.814126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b659271f9961'
down_revision = 'f88362d58ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_warning_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_user', schema=None) as batch_op:
        batch_op.drop_column('last_warning_message')

    # ### end Alembic commands ###
