"""Add RBAC lock revision block

Revision ID: f88362d58ca8
Revises: 70078e6e70d1
Create Date: 2026-09-15 03:31:24.888195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f88362d58ca8'
down_revision = '70078e6e70d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('edited_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['data_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_revisions_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_revisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_revisions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False))
        batch_op.drop_constraint(batch_op.f('articles_slug_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_articles_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_slug'), ['slug'], unique=True)

    with op.batch_alter_table('data_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('warning_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_user', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('warning_count')
        batch_op.drop_column('is_blocked')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_slug'))
        batch_op.drop_index(batch_op.f('ix_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_articles_category'))
        batch_op.create_unique_constraint(batch_op.f('articles_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('is_locked')

    with op.batch_alter_table('article_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_revisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_article_revisions_created_at'))
        batch_op.drop_index(batch_op.f('ix_article_revisions_article_id'))

    op.drop_table('article_revisions')
    # ### end Alembic commands ###
